### ISSUE TITLE
[BUG]按键单击以及多击的实现/  无法区分多组按键

### ISSUE THREAD

**Issue by xiaoxu5271** [xiaolongba/wireless-tech#12]
/软件/红旭无线开发板实战教程对应源码/ESP32/ESP32的第二课：按键单击以及多击的实现/app/

设置多组按键时，传出去的只是第一组的引脚编号
![image](https://user-images.githubusercontent.com/48575240/110742620-abca2880-8271-11eb-8c79-4571138e764c.png)
key_config_t *s_key_config = (key_config_t *)arg;   这个arg 应该是具体到哪组按键，而实际这个是整个按键的配置参数

![image](https://user-images.githubusercontent.com/48575240/110742649-b2f13680-8271-11eb-82f0-20699bc85b13.png)

![image](https://user-images.githubusercontent.com/48575240/110742656-b8e71780-8271-11eb-835e-a96da205ab1e.png)

目前我用的解决办法是设置一个全局变量，用来存放是具体哪组按键触发，

`
/* 存放具体是第几组按键触发 */

static uint8_t gs_key_no = 0;

/** 

 * 消抖之后的按键处理函数,判断是哪个GPIO口以及对应的电平

 * @param[in]   arg   :"esp_decounce_timer"消抖定时器传进来的值,此处没有传进值来

 * @retval      NULL                            

 * @par         修改日志 

 *               Ver0.0.1:

                     Helon_Chan, 2018/06/16, 初始化版本\n 

 */

static void after_key_decounce_cb(void *arg)

{

    // printf("after_key\n");

    /* 轮询判断是哪个GPIO */

    for (uint8_t i = 0; i < gs_key_counts; i++)

    {

        key_config_t *local_key_config = (gs_m_key_config + i);

        uint64_t key_mask = 1ULL << (local_key_config->key_number);

        /* 消抖之后,如果找到对应的GPIO的电平发生转移,则再判断电平是否与进入中断时一致 */

        if (gs_key_transition & key_mask)

        {

            /* 将对应的gpio电平转移标志位清0 */

            gs_key_transition &= ~key_mask;

            bool key_level = gpio_get_level(local_key_config->key_number);

            /* 如果消抖之后的电平与进来中断时的电平是一致的,可以认为按键稳定下来了,且是稳定了 */

            if ((gs_key_state & (1ULL << local_key_config->key_number)) ==

                (((uint64_t)key_level) << local_key_config->key_number))

            {

                gs_key_no = i;

                short_pressed_cb(i, key_level);

            }

        }

    }

}

/** 

 * 计时150ms的时间处理

 * @param[in]   arg   :"esp_short_press_timer"按键完全动作计时器传进来的值,此处传进来的按键短按的次数以及对应的按键

 * @retval      NULL                            

 * @par         修改日志 

 *               Ver0.0.1:

                     Helon_Chan, 2018/06/16, 初始化版本\n 

 */

static void short_press_time_out_handle(void *arg)

{

    key_config_t *s_key_config = (key_config_t *)arg + gs_key_no;

    // ESP_LOGI(TAG, "%d,key_num:%d", __LINE__, s_key_config->key_number);

    gs_m_key_param.short_press_callback(s_key_config->key_number, &(s_key_config->short_pressed_counts));

}

/** 

 * 计时长按时间处理

 * @param[in]   arg   :"esp_long_press_timer"按键长按时计时器传进来的值,此处传进来的按键短按的次数以及对应的按键

 * @retval      NULL                            

 * @par         修改日志 

 *               Ver0.0.1:

                     Helon_Chan, 2018/06/16, 初始化版本\n 

 */

static void long_press_time_out_handle(void *arg)

{

    key_config_t *s_key_config = (key_config_t *)arg + gs_key_no;

    ESP_LOGI(TAG, "%d,key_num:%d", __LINE__, s_key_config->key_number);

    gs_m_key_param.long_press_callback(s_key_config->key_number, &(s_key_config->short_pressed_counts));

}

`

**Comment by xiaolongba** [comment]
感谢老哥提醒，后继我会合并进去
