### ISSUE TITLE
"按键单击以及多击的实现"：如何注册多个GPIO？

### ISSUE THREAD

**Issue by liwmj** [xiaolongba/wireless-tech#15]
**前言**
十分感谢作者贡献出这么优秀的按键代码，在实际试用中感受到了强大，能短/连/长等多个操作，可谓esp32最强按键代码，向作者致敬！

**您的功能请求是否与问题相关？请描述一下**
我的需求是：实现多个GPIO按键的注册和使用，比如IO2、IO4、IO13、IO20等毫无顺序的IO注册并使用。

**描述您想要的解决方案**
能指定几个IO口进行init（或一个接口调用多次）。

**目前的使用状况**
这是打印出来的io口（我定义了4个，但实际是一个io口）
<img width="899" alt="截屏2021-09-07 上午11 29 39" src="https://user-images.githubusercontent.com/2976366/132280842-ea56d967-eec4-4ab8-9314-1d8755c42b39.png">

**配置信息**
只改了io宏
![image](https://user-images.githubusercontent.com/2976366/132280832-7e5573c1-9349-4752-a512-27761d8c0059.png)

**最后**
感谢感谢

**Comment by xiaolongba** [comment]
@liwmj 你可以参照这个[ticket](https://github.com/xiaolongba/HX_DK_FOR_NORDIC_52840_BLE/issues/12#issue-828783651),已经有网友帮我修复这个问题了，嘿嘿

**Comment by liwmj** [comment]
大佬在线啊，哈哈

这个ticket我也看了，但不知道咋改。。。
目前我用的就是最新的代码，要如何使用？

**Comment by xiaolongba** [comment]
> 大佬在线啊，哈哈
> 
> 这个ticket我也看了，但不知道咋改。。。
> 目前我用的就是最新的代码，要如何使用？

这个我目前没有合并，你还需要根据网友的去修改。因为我一直没有去测试过。

**Comment by liwmj** [comment]
搞定了，按照ticket的实际操作是可行的，tks
