### ISSUE TITLE
nRF52840 Mini 红旭主板没法通过nRF Connet/nrfutil 刷固件

### ISSUE THREAD

**Issue by snowyu** [xiaolongba/wireless-tech#6]
插上 UART USB能够看到增加的COM端口 CP210x。
但是nRFConnect软件报告是未知的设备。

插 USB 端口没有任何反应。

**Comment by xiaolongba** [comment]
@snowyu 你有查看我那个重刷固件的教程吗？
[重刷固件教程](https://github.com/xiaolongba/HX_DK_FOR_NORDIC_52840_BLE/blob/master/%E8%BD%AF%E4%BB%B6/%E7%BA%A2%E6%97%AD%E6%97%A0%E7%BA%BF%E5%BC%80%E5%8F%91%E6%9D%BF%E5%AE%9E%E6%88%98%E6%95%99%E7%A8%8B/nRF52840%20Dongle/%E5%A6%82%E4%BD%95%E4%BF%AE%E5%A4%8D%E6%88%96%E8%80%85%E6%9B%B4%E6%96%B0nRF52840%20Dongle%E5%9B%BA%E4%BB%B6.md)

**Comment by snowyu** [comment]
* 编译后的 Bootloader 用什么刷到设备上？如果是用`nrfutil dfu`,那么根本不能识别设备，没法刷啊
* 我不想装IDE, 可以直接用 gcc 工具链编译么？

BTW: Ubuntu 18.10 is my favorite os.

**Comment by snowyu** [comment]
@xiaolongba  对了，刷固件前，是需要按住什么键？对于默认来说.

**Comment by xiaolongba** [comment]
@snowyu 你只要下载了bootloader就可以，接下来的工作由上位机的nrf connect来做，注意看bootloader的log信息，有的时候卡住了需要复位一下才能继续

**Comment by xiaolongba** [comment]
@snowyu of course, you can download the bootloader by the nrf tuil tool without any IDEs. the details about the nrftuil pls refer to its user manual.but I don't recommend to replace the ses IDE with GCC toolchain at first. the usage about how to upgrade the bootloader firmware, pls refer to the tutorial I sent to you before. by the way, any results pls let me know. thanks.

**Comment by snowyu** [comment]
串口看得见，但是连不上, 连都连不上，也就谈不上看日志了。

```bash
$>dmesg
[ 9195.332097] usb 1-1: new full-speed USB device number 13 using xhci_hcd
[ 9195.483348] usb 1-1: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[ 9195.483350] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9195.483351] usb 1-1: Product: CP2102 USB to UART Bridge Controller
[ 9195.483353] usb 1-1: Manufacturer: Silicon Labs
[ 9195.483353] usb 1-1: SerialNumber: 0001
[ 9196.013968] usbcore: registered new interface driver usbserial_generic
[ 9196.014244] usbserial: USB Serial support registered for generic
[ 9196.016397] usbcore: registered new interface driver cp210x
[ 9196.016410] usbserial: USB Serial support registered for cp210x
[ 9196.016433] cp210x 1-1:1.0: cp210x converter detected
[ 9196.018126] usb 1-1: cp210x converter now attached to ttyUSB0
$> ls -l /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 0 Mar 22 08:22 /dev/ttyUSB0
$> nrfutil dfu usb-serial -pkg nrf52840_app_v1.0.0_mdk.zip  -p /dev/ttyUSB0
LIBUSB_ERROR_ACCESS: Unable to connect to trigger interface.
```

在rf connection也是一样，选择它的串口后，报告无法识别的设备。

怀疑是没有进入bootloader模式。

**Comment by xiaolongba** [comment]
@snowyu maybe you are misunderstanding. as you know, the Nordic 52840 mini has two USB interfaces, one is USB to ttl, another is the real USB. you should connect the real USB to the PC after downloading the bootloader firmware , not the USB to ttl.

about the log information, you can see them via link rtt. the ses ide can implement this feature inside.

**Comment by snowyu** [comment]
如果是real usb，dmesg 没有任何反应，难道是坏掉的？

**Comment by xiaolongba** [comment]
That is impossible; the USB is one peripheral of Nordic 52840. Only you download the bootloader into the Mini board, and then it can emulate one UART. The next steps can be finished via nrf connect automatically.

By the way, you should download the bootloader firmware via jlink first, not uart.

**Comment by snowyu** [comment]
Is there no any bootloader in the mini board build-in? I have to buy a jlink debugger to flash bootloader?

**Comment by xiaolongba** [comment]
@snowyu exactly. The default HX nordic 52840 mini without the bootloader firmware inside.

**Comment by snowyu** [comment]
I think you should write the info into the readme. and the jlinker usage.

btw, I'm good at software development and architecture, not hardware.

**Comment by xiaolongba** [comment]
@snowyu thanks for your great advice. I will do it soon.
