### ISSUE TITLE
请问nRF52840Mini开发板的用户手册是哪个？

### ISSUE THREAD

**Issue by ermaerma** [xiaolongba/wireless-tech#7]
请问nRF52840Mini开发板的用户手册是nordic官网的nRF52840_PDK_User_Guide吗？

**Comment by xiaolongba** [comment]
@ermaerma  the kit you purchased is the difference from the official dk. so I don't suggest to refer to this user guide.

**Comment by xiaolongba** [comment]
i close this issue first; any needs for help, you can reopen it. Thanks.
