### ISSUE TITLE
请问下这个板子用keil编译蓝牙5有相关说明吗？

### ISSUE THREAD

**Issue by Jeff-619** [xiaolongba/wireless-tech#8]
请问下这个板子用keil编译蓝牙5有相关说明吗？
--- 目前我使用 nRF5_SDK_15.3.0_59ac345\examples\ble_peripheral\ble_app_uart\pca10056\s140\arm5_no_packs 的keil工程没有编译出来呢？ 
首先pack就没有安装成功呢。

**Comment by xiaolongba** [comment]
@Jeff-619 sorry, i dont have such one tutorial about how to build the project via MDK. But i still can give you some suggestions; maybe you can find the pack packages in the root path of SDK. after installing this tool, it is possible you can build your project successfully.

**Comment by xiaolongba** [comment]
I close this issue first; you can reopen it if any needs for help.
